name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
       - name: Print Reading
         run: echo "hello world"
       - name: Print Goodbye
         run: echo "Done - bye!"
